/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import model.Model_User_Account;

/**
 *
 * @author Admin
 */
public class Chat_Title extends javax.swing.JPanel {

    /**
     * Creates new form Chat_Title
     */
    private Model_User_Account user;

    public Model_User_Account getUser() {
        return user;
    }
    
    public Chat_Title() {
        initComponents();
    }
    
    public void setUserName(Model_User_Account user){
        this.user = user;
        labelName.setText(user.getUserName());
        if(user.isStatus()){
            statusActive();
        }else{
            labelActive.setVisible(false);
        }
    }
    
    public void updateUser(Model_User_Account user){
        if(this.user == user){
            labelName.setText(user.getUserName());
            if(user.isStatus()){
                statusActive();
            }else{
                labelActive.setVisible(false);
            }
        }
    }
    
    private void statusActive(){
        labelActive.setText("Active");
    }
    
    public void statusText(String text){
        labelActive.setText(text);
        //set Color cx đc
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        labelName = new javax.swing.JLabel();
        labelActive = new javax.swing.JLabel();

        jLayeredPane1.setLayout(new java.awt.GridLayout(0, 1));

        labelName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelName.setText("Name");
        jLayeredPane1.add(labelName);

        labelActive.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        labelActive.setForeground(new java.awt.Color(0, 204, 51));
        labelActive.setText("Active");
        jLayeredPane1.add(labelActive);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel labelActive;
    private javax.swing.JLabel labelName;
    // End of variables declaration//GEN-END:variables
}
