/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Admin
 */
public class Chat_Item extends javax.swing.JLayeredPane {
    
    private JLabel jlabel;

    /**
     * Creates new form Chat_Item
     */
    public Chat_Item() {
        initComponents();
        txt.setEditable(false);
        txt.setBackground(new Color(0, 0, 0, 0));
        txt.setOpaque(false);
    }
    
    public void setUserProfile(String user){
        JLayeredPane jlayer = new JLayeredPane();
        jlayer.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 0));
        jlayer.setBorder(new EmptyBorder(10, 10, 0, 5));
        txt.setBorder(new EmptyBorder(5, 10, 5, 10));
        JButton cmd = new JButton(user);
        cmd.setFont(new Font("Segoe UI", 1, 14));
        cmd.setCursor(new Cursor(Cursor.HAND_CURSOR));
        cmd.setBorder(null);
        cmd.setContentAreaFilled(false);//loại bỏ vùng chứa button
        cmd.setFocusable(false); //bỏ qua khi chọn 'tab' chẳng hạn
        //set Color, font, tùy ý
        jlayer.add(cmd);
        add(jlayer, 0);
    }
    
    public void setText(String text){
        txt.setText(text);
    }
    
    public void hideText(){
        txt.setVisible(false);
    }
    
    public void setTime(String time){
        JLayeredPane jlayer = new JLayeredPane();
        jlayer.setLayout(new FlowLayout(FlowLayout.RIGHT, 0, 0));
        jlayer.setBorder(new EmptyBorder(0, 5, 10, 5));
        jlabel = new JLabel(time);
        jlabel.setForeground(new Color(110, 110, 110));
        jlabel.setHorizontalTextPosition(JLabel.LEFT);
        jlayer.add(jlabel);
        add(jlayer);
    }
    
    public void setImage(boolean right, Icon... image){
        if(image.length > 0){
            JLayeredPane jlayer = new JLayeredPane();
            jlayer.setLayout(new FlowLayout(right ? FlowLayout.RIGHT : FlowLayout.LEFT));
            jlayer.setBorder(new EmptyBorder(0, 5, 10, 5));
            Chat_Image chatImage = new Chat_Image(right);
            chatImage.addImage(image);
            jlayer.add(chatImage);
            add(jlayer);
        }
    }
    
    public void setImage(boolean right, String... image) {
        JLayeredPane layer = new JLayeredPane();
        layer.setLayout(new FlowLayout(right ? FlowLayout.RIGHT : FlowLayout.LEFT));
        layer.setBorder(new EmptyBorder(0, 5, 0, 5));
        Chat_Image chatImage = new Chat_Image(right);
        chatImage.addImage(image);
        layer.add(chatImage);
        add(layer);
    }
    
    public void sendSuccess(){
        if(jlabel != null){
            jlabel.setIcon(new ImageIcon(getClass().getResource("/icons/sent.png")));
        }
    }

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        super.paintComponent(grphcs);
    }
    
    public void setFile(String fileName, String fileSize) {
        JLayeredPane layer = new JLayeredPane();
        layer.setLayout(new FlowLayout(FlowLayout.LEFT));
        layer.setBorder(new EmptyBorder(0, 5, 0, 5));
        Chat_File chatFile = new Chat_File();
        chatFile.setFile(fileName, fileSize);
        layer.add(chatFile);
        add(layer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt = new Swing.JIMSendTextPane();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        txt.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        txt.setSelectionColor(new java.awt.Color(0, 153, 255));
        add(txt);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.JIMSendTextPane txt;
    // End of variables declaration//GEN-END:variables
}
