/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import Swing.ScrollBar;
import component.Item_People;
import events.EventMenuLeft;
import events.PublicEvent;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import model.Model_User_Account;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Admin
 */
public class Menu_Left extends javax.swing.JPanel {

    /**
     * Creates new form Menu_Left
     */
    private List<Model_User_Account> userAccount;
    
    public Menu_Left() {
        initComponents();
        init();
    }
    
    private void init(){
        menuList.setLayout(new MigLayout("fillx", "0[]0", "1[]1"));
        userAccount = new ArrayList<Model_User_Account>();
        PublicEvent.getInstance().addEventMenuLeft(new EventMenuLeft(){
            @Override
            public void newUser(List<Model_User_Account> users) {
                for(Model_User_Account d : users){
                    userAccount.add(d);
                    menuList.add(new Item_People(d), "wrap");
                    menuList.repaint();
                    menuList.revalidate();
                }
            }

            @Override
            public void userConnect(int userID) {
                for(Model_User_Account u : userAccount){
                    if(u.getUserID() == userID){
                        u.setStatus(true);
                        
                        break;
                    }
                }
                
                for(Component com : menuList.getComponents()){
                    Item_People item = (Item_People) com;
                    if(item.getUser().getUserID() == userID){
                        item.updateStatus();
                        break;
                    }
                }
              
            }

            @Override
            public void userDisconnect(int userID) {
                for(Model_User_Account u : userAccount){
                    if(u.getUserID() == userID){
                        u.setStatus(false);
                        PublicEvent.getInstance().getEventMain().updateUser(u);
                        break;
                    }
                }
                
                for(Component com : menuList.getComponents()){
                    Item_People item = (Item_People) com;
                    if(item.getUser().getUserID() == userID){
                        item.updateStatus();
                        break;
                    }
                }
            }
            
        });
        
        sp.setVerticalScrollBar(new ScrollBar());
        showMessage();
    }
    
    private void showMessage(){
        menuList.removeAll();
        for(Model_User_Account d : userAccount){
            menuList.add(new Item_People(null), "wrap");
        }
        menuList.repaint();
        menuList.revalidate();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JLayeredPane();
        menuButton1 = new component.MenuButton();
        sp = new javax.swing.JScrollPane();
        menuList = new javax.swing.JLayeredPane();

        setBackground(new java.awt.Color(255, 255, 255));

        menu.setLayout(new javax.swing.BoxLayout(menu, javax.swing.BoxLayout.LINE_AXIS));

        menuButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/seen.png"))); // NOI18N
        menu.add(menuButton1);

        sp.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        javax.swing.GroupLayout menuListLayout = new javax.swing.GroupLayout(menuList);
        menuList.setLayout(menuListLayout);
        menuListLayout.setHorizontalGroup(
            menuListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        menuListLayout.setVerticalGroup(
            menuListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        sp.setViewportView(menuList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
            .addComponent(sp)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sp))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane menu;
    private component.MenuButton menuButton1;
    private javax.swing.JLayeredPane menuList;
    private javax.swing.JScrollPane sp;
    // End of variables declaration//GEN-END:variables
}
